### ISSUE TITLE
"Python"-it ei tasu tõlkida

### ISSUE THREAD

**Issue by murjam** [KristerV/javaCheatsheet#11]
Praegu on python tõlgitud eesti keelde ("püüton"), kuid see tekitab ilmselt rohkem segadust kui kasu. Kui tudengid näiteks googeldama hakkavad või kunagi seda sõna ise peavad kirjutama. Pealegi on python programmeerimiskeele nimi ning nimesid üldiselt ei tõlgitagi.

Umbes samaväärne oleks kirjutada Java asemel kõikjal "kohv" :D

**Comment by KristerV** [comment]
hea point - fixed https://github.com/KristerV/javaCheatsheet/commit/2cf8db4c8e112b3fec10c4c5aac2a1c959ca2109
